### ISSUE TITLE
Occasional hang in `add-document`

### ISSUE THREAD

**Issue by bruceadams** [bruceadams/wdscli#12]
The hang isn't common. My theory is the hang comes from one of the worker threads dying (with a panic) and the termination code of `add-document` demands that each thread absorb a shutdown message. So, the main thread waits forever.

**Comment by colindean** [comment]
@bruceadams If you don’t figure this out this weekend, I’d like to pair with you to fix this this coming week.

**Comment by bruceadams** [comment]
@colindean sounds great! I just implemented a timeout during shutdown, so at least it doesn't hang forever, but that's just a workaround, not a real solution.

**Comment by bruceadams** [comment]
I figured out what I was doing wrong when I was attempting to gather the `JoinHandle`s into a collection. I was doing a `map` but did not have a `collect()` at the end! Oops 😊

**Comment by colindean** [comment]
👍
